import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthLayout from "@/components/auth-layout";
import DeviceGuard from "@/components/device-gaurd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale: 1,
  // minimumScale: 1,
  userScalable: false,
};

// ${geistSans.variable} ${geistMono.variable}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <head>
        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
      document.addEventListener('wheel', function(e) {
        if (e.ctrlKey) e.preventDefault();
      }, { passive: false });
        document.addEventListener('touchmove', function(e) {
        if (e.touches.length > 1) e.preventDefault();
      }, { passive: false });
      var lastTouchEnd = 0;
      document.addEventListener('touchend', function(e) {
        var now = Date.now();
        if (now - lastTouchEnd <= 300) e.preventDefault();
        lastTouchEnd = now;
      }, false);
      document.addEventListener('gesturestart', function(e) { e.preventDefault(); }, { passive: false });
      document.addEventListener('gesturechange', function(e) { e.preventDefault(); }, { passive: false });
      document.addEventListener('gestureend', function(e) { e.preventDefault(); }, { passive: false });
      document.addEventListener('touchmove', function(e) {
        if (e.touches.length > 1) e.preventDefault();
      }, { passive: false });
    `,
          }}
        /> */}

        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Disable pinch-to-zoom (touch gesture)
              document.addEventListener('wheel', function(e) {
                if (e.ctrlKey) e.preventDefault();
              }, { passive: false });

              // Disable multi-touch zoom
              document.addEventListener('touchmove', function(e) {
                if (e.touches.length > 1) e.preventDefault();
              }, { passive: false });

              // Disable double-tap zoom
              var lastTouchEnd = 0;
              document.addEventListener('touchend', function(e) {
                var now = Date.now();
                if (now - lastTouchEnd <= 300) e.preventDefault();
                lastTouchEnd = now;
              }, false);

              // Disable Safari gesture events (older API)
              document.addEventListener('gesturestart', function(e) { e.preventDefault(); }, { passive: false });
              document.addEventListener('gesturechange', function(e) { e.preventDefault(); }, { passive: false });
              document.addEventListener('gestureend', function(e) { e.preventDefault(); }, { passive: false });
            `,
          }}
        />
      </head>
      <body className="h-dvh w-screen overflow-x-hidden flex flex-col">
        {/* <DeviceGuard>{children}</DeviceGuard> */}
        {children}
      </body>
    </html>
  );
}
